---
language: python
python: "2.7"

sudo: required

install:
  - pip install ansible
  - cd tests/
  - echo -e "[defaults]\nroles_path = ../../\nhostfile = inventory" > ansible.cfg
  - echo "localhost" > inventory

script:
  - bash test.sh
